server:
  port: 7001

eureka:
#  instance:
#    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    register-with-eureka: false
    fetch-registry: false
